$(".wine1").click(
 function(){
   $(".text1").text("玉山台灣特級紅高粱");
   $(".text1").css("font-size","40px");
   $(".text1").css("top","80px");
   $(".text2").html("這瓶是上等紅高粱喔!<br>裡面含有單寧酸質、胡蘿蔔素等物質<br>經過2年酒甕儲藏後再固態發酵釀成。");
   $(".text2").css("font-size","25px");
   $(".text2").css("top","200px");
   // $(".wine1").css("animation","ani3 0.5s infinite");
   $(".wine1").css("width","50%");
   $(".wine1").css("height","400px");
   $(".wine1").css("top","80px");
   $(".wine1").css("left","660px");
   $(".wine2").css("top","90px");
   $(".wine2").css("left","330px");
   $(".wine2").css("width","10%");
   $(".wine2").css("height","100px");
   // $(".wine2").css("animation","ani2 0.5s infinite");
   $(".wine3").css("top","90px");
   $(".wine3").css("left","520px");
   $(".wine3").css("width","10%");
   $(".wine3").css("height","100px");  
   // $(".wine3").css("animation","ani2 0.5s infinite");
   $(".wine4").css("top","230px");
   $(".wine4").css("left","150px");
   $(".wine4").css("width","10%");
   $(".wine4").css("height","100px");  
   // $(".wine4").css("animation","ani2 0.5s infinite");
   $(".wine5").css("top","230px");
   $(".wine5").css("left","325px");
   $(".wine5").css("width","10%");
   $(".wine5").css("height","100px");  
   // $(".wine5").css("animation","ani1 0.5s infinite");
   $(".wine6").css("top","230px");
   $(".wine6").css("left","520px");
   $(".wine6").css("width","10%");
   $(".wine6").css("height","100px");  
   // $(".wine6").css("animation","ani2 0.5s infinite");
   $(".wine7").css("top","380px");
   $(".wine7").css("left","440px");
   $(".wine7").css("width","10%");
   $(".wine7").css("height","100px");  
   // $(".wine7").css("animation","ani1 0.5s infinite");
   $(".wine8").css("top","380px");
   $(".wine8").css("left","230px");
   $(".wine8").css("width","10%");
   $(".wine8").css("height","100px");  
   // $(".wine8").css("animation","ani2 0.5s infinite");
 }
);
$(".wine2").click(
 function(){
   $(".text1").text("玉山台灣原窖");
   $(".text1").css("font-size","40px");
   $(".text2").html("採用高山冬麥、阿里山泉與古法踩麴醞釀出台灣獨有的大麴塊，經過固態發酵搭配精密的封存技術，甕口以豬血加石灰與宣紙密湖八層封蓋。");
   $(".text2").css("font-size","25px");
   $(".text2").css("top","180px");
   // $(".wine2").css("animation","ani3 0.5s infinite");
   $(".wine2").css("width","50%");
   $(".wine2").css("height","400px");
   $(".wine2").css("top","80px");
   $(".wine2").css("left","660px");
   $(".wine1").css("top","90px");
   $(".wine1").css("left","150px");
   $(".wine1").css("width","10%");
   $(".wine1").css("height","100px");
   // $(".wine1").css("animation","ani1 0.5s infinite");
   $(".wine3").css("top","90px");
   $(".wine3").css("left","520px");
   $(".wine3").css("width","10%");
   $(".wine3").css("height","100px");  
   // $(".wine3").css("animation","ani2 0.5s infinite");
   $(".wine4").css("top","230px");
   $(".wine4").css("left","150px");
   $(".wine4").css("width","10%");
   $(".wine4").css("height","100px");  
   // $(".wine4").css("animation","ani2 0.5s infinite");
   $(".wine5").css("top","230px");
   $(".wine5").css("left","325px");
   $(".wine5").css("width","10%");
   $(".wine5").css("height","100px");  
   // $(".wine5").css("animation","ani1 0.5s infinite");
   $(".wine6").css("top","230px");
   $(".wine6").css("left","520px");
   $(".wine6").css("width","10%");
   $(".wine6").css("height","100px");  
   // $(".wine6").css("animation","ani2 0.5s infinite");
   $(".wine7").css("top","380px");
   $(".wine7").css("left","440px");
   $(".wine7").css("width","10%");
   $(".wine7").css("height","100px");  
   // $(".wine7").css("animation","ani1 0.5s infinite");
   $(".wine8").css("top","380px");
   $(".wine8").css("left","230px");
   $(".wine8").css("width","10%");
   $(".wine8").css("height","100px");  
   // $(".wine8").css("animation","ani2 0.5s infinite");
 }
);
$(".wine3").click(
 function(){
   $(".text1").text("玉山台灣高粱酒");
   $(".text1").css("font-size","40px");
   $(".text2").text("以高粱、小麥為原料，經過固態發酵、固態蒸餾的方式，再貯藏熟成。酒齡6個月以上，屬於清香型大曲高粱酒，清澈透明、酒烈味濃、醇厚。");
   $(".text2").css("font-size","25px");
   $(".text2").css("top","180px");
   // $(".wine3").css("animation","ani3 0.5s infinite");
   $(".wine3").css("width","50%");
   $(".wine3").css("height","400px");
   $(".wine3").css("top","80px");
   $(".wine3").css("left","660px");
   $(".wine1").css("top","90px");
   $(".wine1").css("left","150px");
   $(".wine1").css("width","10%");
   $(".wine1").css("height","100px");
   // $(".wine1").css("animation","ani1 0.5s infinite");
   $(".wine2").css("top","90px");
   $(".wine2").css("left","330px");
   $(".wine2").css("width","10%");
   $(".wine2").css("height","100px");
   // $(".wine2").css("animation","ani2 0.5s infinite");
   $(".wine4").css("top","230px");
   $(".wine4").css("left","150px");
   $(".wine4").css("width","10%");
   $(".wine4").css("height","100px");  
   // $(".wine4").css("animation","ani2 0.5s infinite");
   $(".wine5").css("top","230px");
   $(".wine5").css("left","325px");
   $(".wine5").css("width","10%");
   $(".wine5").css("height","100px");  
   // $(".wine5").css("animation","ani1 0.5s infinite");
   $(".wine6").css("top","230px");
   $(".wine6").css("left","520px");
   $(".wine6").css("width","10%");
   $(".wine6").css("height","100px");  
   // $(".wine6").css("animation","ani2 0.5s infinite");
   $(".wine7").css("top","380px");
   $(".wine7").css("left","440px");
   $(".wine7").css("width","10%");
   $(".wine7").css("height","100px");  
   // $(".wine7").css("animation","ani1 0.5s infinite");
   $(".wine8").css("top","380px");
   $(".wine8").css("left","230px");
   $(".wine8").css("width","10%");
   $(".wine8").css("height","100px");  
   // $(".wine8").css("animation","ani2 0.5s infinite");
 }
);
$(".wine4").click(
 function(){
   $(".text1").text("玉山大曲");
   $(".text1").css("font-size","40px");
   $(".text2").html("嚴選優質高粱米以及搭配小麥，<br>培育品質優良之酒麴。<br>醒酒後底層帶有梅醬香以及檜木香。");
   $(".text2").css("font-size","25px");
   // $(".wine4").css("animation","ani3 0.5s infinite");
   $(".wine4").css("width","50%");
   $(".wine4").css("height","400px");
   $(".wine4").css("top","80px");
   $(".wine4").css("left","660px");
   $(".wine1").css("top","90px");
   $(".wine1").css("left","150px");
   $(".wine1").css("width","10%");
   $(".wine1").css("height","100px");
   // $(".wine1").css("animation","ani1 0.5s infinite");
   $(".wine2").css("top","90px");
   $(".wine2").css("left","330px");
   $(".wine2").css("width","10%");
   $(".wine2").css("height","100px");
   // $(".wine2").css("animation","ani2 0.5s infinite");
   $(".wine3").css("top","90px");
   $(".wine3").css("left","520px");
   $(".wine3").css("width","10%");
   $(".wine3").css("height","100px");  
   // $(".wine3").css("animation","ani2 0.5s infinite");
   $(".wine5").css("top","230px");
   $(".wine5").css("left","325px");
   $(".wine5").css("width","10%");
   $(".wine5").css("height","100px");  
   // $(".wine5").css("animation","ani1 0.5s infinite");
   $(".wine6").css("top","230px");
   $(".wine6").css("left","520px");
   $(".wine6").css("width","10%");
   $(".wine6").css("height","100px");  
   // $(".wine6").css("animation","ani2 0.5s infinite");
   $(".wine7").css("top","380px");
   $(".wine7").css("left","440px");
   $(".wine7").css("width","10%");
   $(".wine7").css("height","100px");  
   // $(".wine7").css("animation","ani1 0.5s infinite");
   $(".wine8").css("top","380px");
   $(".wine8").css("left","230px");
   $(".wine8").css("width","10%");
   $(".wine8").css("height","100px");  
   // $(".wine8").css("animation","ani2 0.5s infinite");
  }
);
$(".wine5").click(
 function(){
   $(".text1").text("玉山清香高粱酒");
   $(".text1").css("left","150px");
   $(".text1").css("font-size","40px");
   $(".text2").html("以高粱和小麥進行釀製，<br>聞起來是清香的;喝起來在嘴吧裡會有餘香，濃厚的口感中帶有清爽，受到很多人喜愛且獲得很多獎項喔!");
   $(".text2").css("font-size","25px");
   $(".text2").css("top","180px");
   $(".text2").css("left","150px");
   // $(".wine5").css("animation","ani3 0.5s infinite");
   $(".wine5").css("width","40%");
   $(".wine5").css("height","350px");
   $(".wine5").css("top","120px");
   $(".wine5").css("left","690px");
   $(".wine1").css("top","90px");
   $(".wine1").css("left","150px");
   $(".wine1").css("width","10%");
   $(".wine1").css("height","100px");
   // $(".wine1").css("animation","ani1 0.5s infinite");
   $(".wine2").css("top","90px");
   $(".wine2").css("left","330px");
   $(".wine2").css("width","10%");
   $(".wine2").css("height","100px");
   // $(".wine2").css("animation","ani2 0.5s infinite");
   $(".wine3").css("top","90px");
   $(".wine3").css("left","520px");
   $(".wine3").css("width","10%");
   $(".wine3").css("height","100px");  
   // $(".wine3").css("animation","ani2 0.5s infinite");
   $(".wine4").css("top","230px");
   $(".wine4").css("left","150px");
   $(".wine4").css("width","10%");
   $(".wine4").css("height","100px");  
   // $(".wine4").css("animation","ani2 0.5s infinite");
   $(".wine6").css("top","230px");
   $(".wine6").css("left","520px");
   $(".wine6").css("width","10%");
   $(".wine6").css("height","100px");  
   // $(".wine6").css("animation","ani2 0.5s infinite");
   $(".wine7").css("top","380px");
   $(".wine7").css("left","440px");
   $(".wine7").css("width","10%");
   $(".wine7").css("height","100px");  
   // $(".wine7").css("animation","ani1 0.5s infinite");
   $(".wine8").css("top","380px");
   $(".wine8").css("left","230px");
   $(".wine8").css("width","10%");
   $(".wine8").css("height","100px");  
   // $(".wine8").css("animation","ani2 0.5s infinite");
 }
);
$(".wine6").click(
 function(){
   $(".text1").text("玉山大武醇");
   $(".text1").css("font-size","40px");
   $(".text2").html("取自大武山區優良水質製作，經過多次蒸餾，精心調製而成。香氣濃郁，口感醇厚乾爽。");
   $(".text2").css("font-size","25px");
   // $(".wine6").css("animation","ani3 0.5s infinite");
   $(".wine6").css("width","50%");
   $(".wine6").css("height","400px");
   $(".wine6").css("top","80px");
   $(".wine6").css("left","660px");
   $(".wine1").css("top","90px");
   $(".wine1").css("left","150px");
   $(".wine1").css("width","10%");
   $(".wine1").css("height","100px");
   // $(".wine1").css("animation","ani1 0.5s infinite");
   $(".wine2").css("top","90px");
   $(".wine2").css("left","330px");
   $(".wine2").css("width","10%");
   $(".wine2").css("height","100px");
   // $(".wine2").css("animation","ani2 0.5s infinite");
   $(".wine3").css("top","90px");
   $(".wine3").css("left","520px");
   $(".wine3").css("width","10%");
   $(".wine3").css("height","100px");  
   // $(".wine3").css("animation","ani2 0.5s infinite");
   $(".wine4").css("top","230px");
   $(".wine4").css("left","150px");
   $(".wine4").css("width","10%");
   $(".wine4").css("height","100px");  
   // $(".wine4").css("animation","ani2 0.5s infinite");
   $(".wine5").css("top","230px");
   $(".wine5").css("left","325px");
   $(".wine5").css("width","10%");
   $(".wine5").css("height","100px");  
   // $(".wine5").css("animation","ani1 0.5s infinite");
   $(".wine7").css("top","380px");
   $(".wine7").css("left","440px");
   $(".wine7").css("width","10%");
   $(".wine7").css("height","100px");  
   // $(".wine7").css("animation","ani1 0.5s infinite");
   $(".wine8").css("top","380px");
   $(".wine8").css("left","230px");
   $(".wine8").css("width","10%");
   $(".wine8").css("height","100px");  
   // $(".wine8").css("animation","ani2 0.5s infinite");
  }
);
$(".wine7").click(
 function(){
   $(".text1").text("玉山頂級層高");
   $(".text1").css("font-size","40px");
   $(".text2").text("特選優良高粱、天然小麥、大曲為原料，採傳統工法並結合現代科技所釀製，經歲月自然熟成，酒質特良。");
   $(".text2").css("font-size","25px");
   // $(".wine7").css("animation","ani3 0.5s infinite");
   $(".wine7").css("width","50%");
   $(".wine7").css("height","400px");
   $(".wine7").css("top","80px");
   $(".wine7").css("left","660px");
   $(".wine1").css("top","90px");
   $(".wine1").css("left","150px");
   $(".wine1").css("width","10%");
   $(".wine1").css("height","100px");
   // $(".wine1").css("animation","ani1 0.5s infinite");
   $(".wine2").css("top","90px");
   $(".wine2").css("left","330px");
   $(".wine2").css("width","10%");
   $(".wine2").css("height","100px");
   // $(".wine2").css("animation","ani2 0.5s infinite");
   $(".wine3").css("top","90px");
   $(".wine3").css("left","520px");
   $(".wine3").css("width","10%");
   $(".wine3").css("height","100px");  
   // $(".wine3").css("animation","ani2 0.5s infinite");
   $(".wine4").css("top","230px");
   $(".wine4").css("left","150px");
   $(".wine4").css("width","10%");
   $(".wine4").css("height","100px");  
   // $(".wine4").css("animation","ani2 0.5s infinite");
   $(".wine5").css("top","230px");
   $(".wine5").css("left","325px");
   $(".wine5").css("width","10%");
   $(".wine5").css("height","100px");  
   // $(".wine5").css("animation","ani1 0.5s infinite");
   $(".wine6").css("top","230px");
   $(".wine6").css("left","520px");
   $(".wine6").css("width","10%");
   $(".wine6").css("height","100px");  
   // $(".wine6").css("animation","ani2 0.5s infinite");
   $(".wine8").css("top","380px");
   $(".wine8").css("left","230px");
   $(".wine8").css("width","10%");
   $(".wine8").css("height","100px");  
   // $(".wine8").css("animation","ani2 0.5s infinite");
 }
);
$(".wine8").click(
 function(){
   $(".text1").text("玉山頂級陳高紅麒麟");
   $(".text1").css("font-size","40px");
   $(".text1").css("left","150px");
   $(".text2").html("麒麟是神話中的神獸，長得像馬、尾巴像牛、是很多動物的集合，就像這瓶酒是很多酒類的集合。經過師父仔細雕刻，也象徵著豐富層次和工藝。");
   $(".text2").css("font-size","25px");
   $(".text2").css("left","150px");
   // $(".wine8").css("animation","ani3 0.5s infinite");
   $(".wine8").css("width","35%");
   $(".wine8").css("height","330px");
   $(".wine8").css("top","150px");
   $(".wine8").css("left","700px");
   $(".wine1").css("top","90px");
   $(".wine1").css("left","150px");
   $(".wine1").css("width","10%");
   $(".wine1").css("height","100px");
   // $(".wine1").css("animation","ani1 0.5s infinite");
   $(".wine2").css("top","90px");
   $(".wine2").css("left","330px");
   $(".wine2").css("width","10%");
   $(".wine2").css("height","100px");
   // $(".wine2").css("animation","ani2 0.5s infinite");
   $(".wine3").css("top","90px");
   $(".wine3").css("left","520px");
   $(".wine3").css("width","10%");
   $(".wine3").css("height","100px");  
   // $(".wine3").css("animation","ani2 0.5s infinite");
   $(".wine4").css("top","230px");
   $(".wine4").css("left","150px");
   $(".wine4").css("width","10%");
   $(".wine4").css("height","100px");  
   // $(".wine4").css("animation","ani2 0.5s infinite");
   $(".wine5").css("top","230px");
   $(".wine5").css("left","325px");
   $(".wine5").css("width","10%");
   $(".wine5").css("height","100px");  
   // $(".wine5").css("animation","ani1 0.5s infinite");
   $(".wine6").css("top","230px");
   $(".wine6").css("left","520px");
   $(".wine6").css("width","10%");
   $(".wine6").css("height","100px");  
   // $(".wine6").css("animation","ani2 0.5s infinite");
   $(".wine7").css("top","380px");
   $(".wine7").css("left","440px");
   $(".wine7").css("width","10%");
   $(".wine7").css("height","100px");  
   // $(".wine7").css("animation","ani1 0.5s infinite");
 }
);
$(".button3").mouseenter(
 function(){
   $(this).css("border-bottom","solid 7px #7d4220")
 }
);
$(".button3").mouseleave(
 function(){
   $(this).css("border-bottom","solid 7px transparent")
 }
);